apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1
  version: "1.17"
  tags:
    'tool': 'demo-cluster'
    'env': 'test'

vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-0969db69a154d11f6 }
      us-east-1b: { id: subnet-0570a6b14436a2e62 }
      us-east-1c: { id: subnet-07bdef2a65ef72187 }
    private:
      us-east-1a: { id: subnet-0e3b347879edd5f93 }
      us-east-1b: { id: subnet-0d88d0f929fecd680 }
      us-east-1c: { id: subnet-0e8ec9d154ac3087b }

managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 3
    volumeSize: 50
    ssh:
      allow: true
      publicKeyName: demokey
    privateNetworking: true
    tags:
      'tool': 'demo-cluster'
      'env': 'test'
